baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'speculatio pauperis in deserto'
theme = "rocinante"
paginate = 7

[markup]
	[markup.highlight]
		style = "monokailight"
	[markup.goldmark.renderer]
		unsafe= true

[params]
	mainSections = ["posts", "photos"]
	email = "ambelfield@gmail.com"
	favicon = "icons/favicon.png"
	about = ""

	[[params.links]]
		[[params.links.link]]
			name = "about me"
			href = "https://andrewbelfield.com"
			new_tab = false
		[[params.links.link]]
			name = "about this blog"
			href = "/about"
		[[params.links.link]]
			name = "about my teaching"
			href = "/teaching"
		[[params.links.link]]
			name = "about my research"
			href = "/research"

	[[params.links]]
		[[params.links.link]]
			name = "my cv"
			href = "/cv"
		[[params.links.link]]
			name = "my micro.blog"
			href = "https://blog.andrewbelfield.com"
			new_tab = false
		[[params.links.link]]
			name = "email me"
			href = "/contact"
			smart_email_link = true
